name: "Feature Request"
description: "Sugira uma nova funcionalidade para o projeto"
title: "[FEATURE] "
labels: ["feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova funcionalidade! Por favor, preencha as informações abaixo para nos ajudar a entender sua solicitação.

  - type: input
    id: description
    attributes:
      label: "Descrição da Funcionalidade"
      description: "Descreva a funcionalidade que você gostaria de ver implementada."
      placeholder: "Digite a descrição aqui"
      required: true