name: New Feature
description: File a feature report.
title: "[FEATURE]: "
labels: ["feature"]
projects: ["atlas-sdk/projects/2"]
assignees:
  - ElbertRibeiro
body:
  - type: dropdown
    id: project
    attributes:
      label: "Escolha um tipo de projeto para ser gerado: "
      options:
        - windows
        - linux
        - mac
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your feature request
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A feature happened!"
    validations:
      required: true
